### ISSUE TITLE
Adding to list of supported languages in highlight.js repo

### ISSUE THREAD

**Issue by ryanditjia** [AlexxNB/highlightjs-svelte#2]
Hi, I made [a PR](https://github.com/highlightjs/highlight.js/pull/2549) to add this package to [this list](https://github.com/highlightjs/highlight.js/blob/master/SUPPORTED_LANGUAGES.md).

There’s a blocker that needs your attention, could you help me with that?

**Comment by AlexxNB** [comment]
Question is about adding the browser module in the dist folder also? Ok, I will add this.

**Comment by AlexxNB** [comment]
Done! =)

**Comment by ryanditjia** [comment]
That was quick. Thanks.
